CREATE TABLE `players` (
	`id` INT(11) NOT NULL AUTO_INCREMENT,
	`name` VARCHAR(32) NOT NULL,
	`password` VARCHAR(32) NULL DEFAULT NULL,
	`group` VARCHAR(32) NULL DEFAULT NULL,
	`last_ip` VARCHAR(16) NULL DEFAULT NULL,
	`last_join` VARCHAR(16) NULL DEFAULT NULL,
	`last_server` VARCHAR(16) NULL DEFAULT NULL,
	`muted_by` VARCHAR(32) NULL DEFAULT NULL,
	`banned_by` VARCHAR(32) NULL DEFAULT NULL,
	`is_banned` TINYINT(1) NOT NULL DEFAULT '0',
	`is_muted` TINYINT(1) NOT NULL DEFAULT '0',
	`mute_amount` TINYINT NOT NULL DEFAULT '0',
	`ban_amount` TINYINT NOT NULL DEFAULT '0',
	`uuid` VARCHAR(64) NOT NULL,
	`total_time` TIMESTAMP NULL DEFAULT NULL,
	`banned_until` TIMESTAMP NULL DEFAULT NULL,
	`muted_until` TIMESTAMP NULL DEFAULT NULL,
	PRIMARY KEY (`id`),
	UNIQUE INDEX `id` (`id`),
	UNIQUE INDEX `name` (`name`)
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB
AUTO_INCREMENT=4
;
