name: Core
version: 0.7.0
main: org.kvlt.core.bukkit.CorePlugin
commands:
  alert:
    usage: /alert <text>
  salert:
    usge: /salert <server> <message>
  msg:
    usage: /msg <to> <text>
    aliases: [tell, m, w, t, whisper, pm, message]
  time:
    usage: /time [player]
  hub:
    alises: [lobby]
    usage: /hub
  sendcommand:
    aliases: [sc]
    usage: /sc <server> <command>
  reply:
    aliases: [r, rep]
    usage: /r <message>
  con:
    aliases: [core, coreconnect, cc]
    usage: /con
  server:
    usage: /server <server_name>
  ban:
    usage: /ban
  send:
    usage: /send <who> <where>